// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using book_app_server.Models;

namespace book_app_server.Migrations
{
    [DbContext(typeof(BookappContext))]
    [Migration("20190709160744_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("book_app_server.Models.Book", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<long>("BookShelfId");

                    b.Property<string>("ISBN");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("BookShelfId");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("book_app_server.Models.BookShelf", b =>
                {
                    b.Property<long>("BookShelfId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("BookShelfId");

                    b.ToTable("Bookshelf");
                });

            modelBuilder.Entity("book_app_server.Models.Book", b =>
                {
                    b.HasOne("book_app_server.Models.BookShelf")
                        .WithMany("Books")
                        .HasForeignKey("BookShelfId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
